version: "3.2"
services:

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:3
    restart: unless-stopped
    ports:
      - "6379:6379"

  rails:
    build:
      context: ./
      dockerfile: Dockerfile-rails
    restart: unless-stopped
    environment:
      RAILS_ENV: development
    ports:
      - "8080:8080"
    volumes:
      - rails-log:/home/app/log
    depends_on:
      - redis
      - mysql
    links:
      - redis
      - mysql

  resque:
    build:
      context: ./
      dockerfile: Dockerfile-resque
    volumes:
      - resque-log:/usr/src/app/log
    restart: unless-stopped
    environment:
      RAILS_ENV: development
    depends_on:
      - redis
      - mysql
    links:
      - redis
      - mysql

volumes:
  mysql-data:
    driver: local
  rails-log:
    driver: local
  resque-log:
    driver: local
