default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: /home/db/development.sqlite3

test:
  <<: *default
  database: /home/db/test.sqlite3

production:
  <<: *default
  database: /home/db/production.sqlite3
